# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [5]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [6]:
# your code here
!pip install numpy

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [8]:
# Method 1
a = np.random.random(size = (2,3,5))
a

array([[[0.97214664, 0.30649553, 0.59352501, 0.01665127, 0.87304613],
        [0.23256386, 0.41787727, 0.56880052, 0.67574376, 0.94688373],
        [0.28208122, 0.34848062, 0.1173424 , 0.22191048, 0.59631872]],

       [[0.19736257, 0.66649098, 0.86823437, 0.19620985, 0.3408706 ],
        [0.71834449, 0.43739464, 0.21552311, 0.52379016, 0.21665089],
        [0.96787899, 0.89746265, 0.97443851, 0.6197979 , 0.21477339]]])

In [17]:
# Method 2
a = np.random.rand(2,3,5)
a

array([[[0.40055614, 0.67235309, 0.74581842, 0.74613548, 0.90537446],
        [0.00408   , 0.33508906, 0.53603529, 0.85113794, 0.76233604],
        [0.23894762, 0.55436266, 0.74161346, 0.08377697, 0.83152488]],

       [[0.74810774, 0.01757252, 0.34483717, 0.43321243, 0.24887911],
        [0.99549632, 0.9288374 , 0.9465631 , 0.99726655, 0.04709071],
        [0.02213873, 0.58205103, 0.64320421, 0.12647146, 0.7775028 ]]])

In [20]:
# Method 3
a = np.random.random_sample(size = (2,3,5))
a

array([[[0.31862869, 0.33694255, 0.30627623, 0.83557201, 0.448242  ],
        [0.22522085, 0.0634502 , 0.58171519, 0.57903115, 0.6683231 ],
        [0.46895461, 0.91865632, 0.62345344, 0.41073604, 0.57401673]],

       [[0.78355319, 0.2689891 , 0.75885853, 0.37287024, 0.62320668],
        [0.28654527, 0.06383888, 0.07595581, 0.47946435, 0.76823403],
        [0.11589099, 0.22203184, 0.05444898, 0.04849742, 0.06239247]]])

#### 4. Print *a*.


In [21]:
# your code here
print(a)

[[[0.31862869 0.33694255 0.30627623 0.83557201 0.448242  ]
  [0.22522085 0.0634502  0.58171519 0.57903115 0.6683231 ]
  [0.46895461 0.91865632 0.62345344 0.41073604 0.57401673]]

 [[0.78355319 0.2689891  0.75885853 0.37287024 0.62320668]
  [0.28654527 0.06383888 0.07595581 0.47946435 0.76823403]
  [0.11589099 0.22203184 0.05444898 0.04849742 0.06239247]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [25]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [26]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [27]:
# your code here
np.size(a) == np.size(b)

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [28]:
# your answer here
a + b

## not able, because the different of shapes

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Reshape *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the reshaped array to variable *c*.

In [29]:
# your code here
c = np.reshape(b, (2,3,5))

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [31]:
# your code/answer here
d = a + c

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [35]:
# your code/answer here
print(f'a = {a}',f'\n\nd ={d}')

a = [[[0.31862869 0.33694255 0.30627623 0.83557201 0.448242  ]
  [0.22522085 0.0634502  0.58171519 0.57903115 0.6683231 ]
  [0.46895461 0.91865632 0.62345344 0.41073604 0.57401673]]

 [[0.78355319 0.2689891  0.75885853 0.37287024 0.62320668]
  [0.28654527 0.06383888 0.07595581 0.47946435 0.76823403]
  [0.11589099 0.22203184 0.05444898 0.04849742 0.06239247]]] 

d =[[[1.31862869 1.33694255 1.30627623 1.83557201 1.448242  ]
  [1.22522085 1.0634502  1.58171519 1.57903115 1.6683231 ]
  [1.46895461 1.91865632 1.62345344 1.41073604 1.57401673]]

 [[1.78355319 1.2689891  1.75885853 1.37287024 1.62320668]
  [1.28654527 1.06383888 1.07595581 1.47946435 1.76823403]
  [1.11589099 1.22203184 1.05444898 1.04849742 1.06239247]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [36]:
# your code here
e = a * c

#### 13. Does *e* equal to *a*? Why or why not?


In [37]:
# your code/answer here
e == a

#Yes, same shape and C it's a ones.

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [59]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print(d)
print(d_max, d_min, d_mean)

[[[1.31862869 1.33694255 1.30627623 1.83557201 1.448242  ]
  [1.22522085 1.0634502  1.58171519 1.57903115 1.6683231 ]
  [1.46895461 1.91865632 1.62345344 1.41073604 1.57401673]]

 [[1.78355319 1.2689891  1.75885853 1.37287024 1.62320668]
  [1.28654527 1.06383888 1.07595581 1.47946435 1.76823403]
  [1.11589099 1.22203184 1.05444898 1.04849742 1.06239247]]]
1.918656324733163 1.0484974153902915 1.4114665617470885


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [148]:
# your code here
f = np.empty((2,3,5))

In [79]:
np.shape(d)

(2, 3, 5)

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [149]:
# your code here
for arrays in range(2):
    for columns in range(3):
         for rows in range(5):
            elements = d[arrays][columns][rows]
            if (elements>d_min) and (elements<d_mean):
                 elements = 25
            elif (elements>d_mean) and (elements<d_max):
                elements = 75
            elif (elements == d_mean):
                elements = 50
            elif (elements == d_min):
                elements = 0
            elif (elements == d_max):
                elements = 100
            f[arrays][columns][rows] = elements

In [150]:
print(f)

[[[ 25.  25.  25.  75.  75.]
  [ 25.  25.  75.  75.  75.]
  [ 75. 100.  75.  25.  75.]]

 [[ 75.  25.  75.  25.  75.]
  [ 25.  25.  25.  75.  75.]
  [ 25.  25.  25.   0.  25.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [151]:
# your code here
print(d,'\n\n\n',f)

[[[1.31862869 1.33694255 1.30627623 1.83557201 1.448242  ]
  [1.22522085 1.0634502  1.58171519 1.57903115 1.6683231 ]
  [1.46895461 1.91865632 1.62345344 1.41073604 1.57401673]]

 [[1.78355319 1.2689891  1.75885853 1.37287024 1.62320668]
  [1.28654527 1.06383888 1.07595581 1.47946435 1.76823403]
  [1.11589099 1.22203184 1.05444898 1.04849742 1.06239247]]] 


 [[[ 25.  25.  25.  75.  75.]
  [ 25.  25.  75.  75.  75.]
  [ 75. 100.  75.  25.  75.]]

 [[ 75.  25.  75.  25.  75.]
  [ 25.  25.  25.  75.  75.]
  [ 25.  25.  25.   0.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [154]:
f = list(f)

In [167]:
# your code here
g = []
for elements in np.nditer(d):
    if (elements>d_min) and (elements<d_mean):
        elements = 'B'
    elif (elements>d_mean) and (elements<d_max):
        elements = 'D'
    elif (elements == d_mean):
        elements = 'C'
    elif (elements == d_min):
        elements = 'A'
    elif (elements == d_max):
        elements = 'E'
    g.append(elements)
g = np.reshape(g,(3,2,5))
g

array([[['B', 'B', 'B', 'D', 'D'],
        ['B', 'B', 'D', 'D', 'D']],

       [['D', 'E', 'D', 'B', 'D'],
        ['D', 'B', 'D', 'B', 'D']],

       [['B', 'B', 'B', 'D', 'D'],
        ['B', 'B', 'B', 'A', 'B']]], dtype='<U1')